Add myself (Patrik Svensson)
WeAreDotnet/dotnet-creator-cards pull request #74
Opened 2023-03-15 10:58 UTC by patriksvensson

# #WeAreDonet Creator Submission Guidelines

* By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* We do not accept submissions with the sole intention of promoting a product or company.

* We add you as a creator, not your company. 

* The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* You must have published a post since 2022 on any of your channels. 

* There must be one publication in English. 

* There needs to be more than tweets. 

* A longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* If you do not submit an RSS or Atom URL. We cannot consider your feed for the upcoming aggregation feature. 

## Content Guideline 

* If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

2023-03-16 12:20 UTC, DeeJayTC commented on creator-cards/patrik-svensson.json
> +      "url": "https://patriksvensson.se/atom.xml"
If both feed types return the same results just give us one tho we don't have to filter dublicates

2023-03-16 12:20 UTC, DeeJayTC requested changes
Can you please give us a feed that's filtered for .NET and related content? I've seen a couple of Rust posts in the feed

2023-03-16 12:21 UTC, patriksvensson commented
Ah, I'll remove the feed altogether then when I'm at a computer.

2023-04-01 10:16 UTC, patriksvensson commented
Updated

2023-04-03 20:06 UTC, DeeJayTC commented
So just double checking, you do not have a feed purely with .NET content and only want your channels listed?

2023-04-03 21:13 UTC, patriksvensson commented
Correct. Not a one trick pony 😉

2023-04-10 21:23 UTC, patriksvensson commented
No rush

2023-04-30 09:55 UTC, matthiasjost commented
Any updates on this?

There is a new format allows one to have projects: https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

2023-04-30 10:05 UTC, patriksvensson commented
Ah, good to know. Will update with some projects.

2023-10-28 22:02 UTC, arpitsdotnet reviewed
Done

2023-12-02 09:59 UTC, matthiasjost commented
@patriksvensson Any updates on this?

The new card format:
- https://github.com/WeAreDotnet/dotnet-creator-cards#sample-card
- https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

The new settings page:
- https://www.wearedotnet.io/settings

It would be cool to have you onboard!

Greetings

Matthias

2023-12-08 22:28 UTC, closed without merging